name: Citation Check

on:
  push:
    paths: ['CITATION.cff']
  pull_request:
    paths: ['CITATION.cff']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-cff:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate CITATION.cff
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
